Update color-picker.tsx
hirotomoyamada/yamada-ui pull request #725
Opened 2024-02-11 06:37 UTC by AllenWasupan

support #724

Closes # 

## Description

> Add a brief description

## Current behavior (updates)

> Please describe the current behavior that you are modifying

## New behavior

> Please describe the behavior or changes this PR adds

## Is this a breaking change (Yes/No):

## Additional Information

2024-02-11 06:52 UTC, hirotomoyamada commented
Please, create the file using the `pnpm changeset` command and see `contributing.md`.

2024-02-11 06:53 UTC, hirotomoyamada commented
@AllenWasupan 

Hi, thanks for the PR!

Please, create the file using the `pnpm changeset` command and see `CONTRIBUTING.md`.

2024-02-11 15:39 UTC, KenyaMasuko requested changes
Hi, thank you for your contributing!

I've listed several points that need to be revised. Please check them out! Also, when making a pull request, please ensure to do so from the appropriate branch in accordance with the [contribution guide](https://github.com/hirotomoyamada/yamada-docs/blob/main/CONTRIBUTING.md#steps-to-pr)!

Keep it up💪

2024-02-11 15:39 UTC, KenyaMasuko commented on packages/components/color-picker/src/color-picker.tsx
> +  >
The type `channelProps` isn't included in type `ColorSelectorProps` ( from `color-selector.tsx`), so you may want to consider augmenting the typing as follows in `color-selector.tsx`:
```tsx
  export type ColorSelectorProps = ThemeProps<"ColorSelector"> &
    UseColorSelectorProps &
    ColorSelectorOptions &
    Pick<
      ColorSelectorBodyProps,
      | "withResult"
      | "withEyeDropper"
      | "eyeDropperRef"
      | "eyeDropperProps"
      | "hueSliderRef"
      | "hueSliderProps"
      | "alphaSliderRef"
      | "alphaSliderProps"
    > &
    Pick<
      ColorSelectorSwatchesProps,
      "swatchesLabel" | "swatches" | "swatchesColumns" | "swatchProps"
    > &
    ColorSelectorChannelsProps // add this
```
The type `ColorSelectorChannelsProps` includes the `channelProps` property.

And in color-selector.tsx, ensure that `channelProps` are received via its props, and then pass `channelProps` to <ColorSelectorChannels /> like this: 
```tsx
const {
    className,
    withResult = true,
    withPicker = true,
    withChannel = true,
    swatches,
    swatchesColumns = 7,
    inputProps,
    withEyeDropper,
    eyeDropperRef,
    eyeDropperProps,
    saturationSliderRef,
    saturationSliderProps,
    hueSliderRef,
    hueSliderProps,
    alphaSliderRef,
    alphaSliderProps,
    swatchesLabel,
    swatchProps,
    swatchesProps,
    channelProps, // add this
    ...computedProps
} = omitThemeProps(mergedProps)

// other codes...

return (
  // other codes...

  {withPicker && withChannel ? (
    <ColorSelectorChannels channelProps={channelProps} /> // add `channelProps`
  ) : null}

  // other codes...
)
```

2024-02-12 15:03 UTC, umaidashi commented on packages/components/color-picker/src/color-picker.tsx
> +     channelProps,
The indentation appears to be misaligned.

2024-02-17 05:43 UTC, hirotomoyamada commented
@AllenWasupan 

This PR has duplicated corrections, so it will be closed.

2024-02-17 05:43 UTC, closed without merging