fix(scroll-area): hide scrollbar behavior on Firefox
hirotomoyamada/yamada-ui pull request #746
Opened 2024-02-17 04:52 UTC by taroj1205

Closes #745 

## Description

Fixed `ScrollArea` for Firefox to hide the scrollbar by default and show only on `hover` or `scroll`, based on the `type` prop.

## Current behavior (updates)

Does not hide the scrollbar by default and always shows even if the type prop is `"hover"` or `"scroll"`.

## New behavior

Fixes this behavior.

## Is this a breaking change (Yes/No):

No

2024-02-17 09:42 UTC, illionillion requested changes
@taroj1205 
Chromeだとスクロールバーが表示されなかったので確認・修正お願いします。

https://github.com/hirotomoyamada/yamada-ui/assets/60034520/e8fe6531-60a8-4e7d-8ba0-debce1b57a8a

2024-02-17 09:42 UTC, illionillion commented on packages/components/scroll-area/src/scroll-area.tsx
> +  scrollbarColor: "transparent transparent",
FireFoxにだけ適用するのなら

```js
"&::-moz-scrollbar-track": {
  scrollbarColor: "transparent transparent",
},
```

がいいと思います。
試しに現在のコードのStorybookでの挙動を確認したらFireFoxでは望まれた挙動はしますが、Chromeでは`hover`や`scroll`時にスクロールバーが表示されませんでした。

一度試してみてください。

2024-02-17 09:42 UTC, illionillion commented on packages/components/scroll-area/src/scroll-area.tsx
> +    scrollbarColor: "transparent transparent",
ここも同じくFireFoxだけにスタイルが当たるようにした方がいいと思います。

2024-02-17 09:42 UTC, illionillion commented on packages/components/scroll-area/src/scroll-area.tsx
> +    scrollbarColor: "transparent transparent",
ここも同じく

2024-02-17 18:57 UTC, taroj1205 commented on packages/components/scroll-area/src/scroll-area.tsx
> +    scrollbarColor: "transparent transparent",
2つ目のcommitで既にFirefoxのみにスタイルが当たるようにしているのでご確認できますか？

2024-02-18 03:47 UTC, illionillion commented on packages/components/scroll-area/src/scroll-area.tsx
> +    scrollbarColor: "transparent transparent",
レビューした後にコミット上げてくれてたんですね、見てみます。

2024-02-18 04:35 UTC, illionillion approved these changes
FireFox・Chromeでも問題なく動作確認できましたので承認します。
Safariの方でもHover・Scrollが正常に動作しないようなので別issueでの修正が必要そうです。

2024-02-18 05:16 UTC, hirotomoyamada commented
@illionillion @taroj1205 

> FireFox・Chromeでも問題なく動作確認できましたので承認します。
> Safariの方でもHover・Scrollが正常に動作しないようなので別issueでの修正が必要そうです。

イシューの作成をお願いします。

2024-02-18 05:16 UTC, merged