Fix/color picker/tokens
hirotomoyamada/yamada-ui pull request #847
Opened 2024-02-27 14:18 UTC by nogu66

…ents

Closes # 

## Description

ColorPickerのtokensを具体値に修正しました。

## Current behavior (updates)
```
w: "full",
h: "full",
```

## New behavior
```
w: "100%",
h: "100%",
```
## Is this a breaking change (No):

## Additional Information

2024-02-27 17:55 UTC, setodeve requested changes

2024-02-27 17:55 UTC, setodeve commented on .changeset/spicy-tools-rule.md
changesetのファイルはpnpm changesetを実行いただいて新規作成お願いします。
こちらのファイルの変更は取り消しお願いします。

2024-02-27 18:06 UTC, hirotomoyamada commented on packages/components/color-picker/src/color-swatch.tsx
> +      {...(isRounded ? { rounded: "100%" } : {})}
```diff
- {...(isRounded ? { rounded: "100%" } : {})}
+ {...(isRounded ? { rounded: "9999px" } : {})}
```

2024-02-27 18:07 UTC, hirotomoyamada commented on packages/components/color-picker/src/color-swatch.tsx
> +            {...(isRounded ? { rounded: "100%" } : {})}
```diff
- {...(isRounded ? { rounded: "100%" } : {})}
+ {...(isRounded ? { rounded: "9999px" } : {})}
```

2024-02-27 18:07 UTC, hirotomoyamada commented on packages/components/color-picker/src/color-swatch.tsx
> +      <ui.div {...(isRounded ? { rounded: "100%" } : {})}>
```diff
- {...(isRounded ? { rounded: "100%" } : {})}
+ {...(isRounded ? { rounded: "9999px" } : {})}
```

2024-02-28 01:18 UTC, setodeve approved these changes

2024-02-28 01:38 UTC, merged