fix: Indicator theme token usage in styles
hirotomoyamada/yamada-ui pull request #849
Opened 2024-02-27 15:55 UTC by Exerea

Hi!
Thanks for posting on Twitter!
I'm happy to try to contribute to this OSS for the first time.
We hope Yamada UI will be a success.

Closes #840

## Description

I fixed a bug where theme tokens were used in components.
I replace from "full" to  "100%".

## Is this a breaking change (Yes/No):

No

2024-02-27 18:02 UTC, setodeve commented
@Exerea 
Hi! Thank you for contributing!
Please create changeset file with executing `pnpm changeset`.

Please refer the following material.
<img width="1142" alt="image" src="https://github.com/hirotomoyamada/yamada-ui/assets/83833293/54c4daac-355c-4dea-a29e-6cd7a45db001">
https://github.com/hirotomoyamada/yamada-ui/blob/main/CONTRIBUTING.md

2024-02-27 18:08 UTC, hirotomoyamada commented on packages/components/indicator/src/indicator.tsx
> +                rounded: "100%",
```diff
- rounded: "100%",
+ rounded: "9999px",
```

2024-02-28 13:33 UTC, setodeve requested changes

2024-02-28 13:33 UTC, setodeve commented on .changeset/rich-suns-rescue.md
> +"@yamada-ui/indicator": minor
Please edit here with a patch, not a minor.

2024-02-28 13:33 UTC, setodeve commented on pnpm-lock.yaml
Please delete this file.

2024-02-28 14:00 UTC, closed without merging

2024-02-28 14:40 UTC, setodeve commented
@Exerea 
Could you reopen this PR if possible?